CREATE TABLE news_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(120) NOT NULL,
    title VARCHAR(1000) NOT NULL,
    url VARCHAR(2048) NOT NULL UNIQUE,
    published_at TIMESTAMP WITH TIME ZONE,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_news_articles_published_at ON news_articles (published_at DESC);
CREATE INDEX idx_news_articles_source ON news_articles (source);
